name: Build Windows Installer

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Set up Maven
      run: mvn -v

    - name: Build App
      run: mvn clean install

    - name: Package with jpackage
      shell: cmd
      run: |
        jpackage --type exe ^
        --input target ^
        --dest installer ^
        --name CleanView ^
        --main-jar CleanView-1.0.jar ^
        --main-class com.sampath.pdfviewer.MainApp ^
        --icon src/main/resources/icon.ico ^
        --win-menu ^
        --win-shortcut ^
        --win-dir-chooser ^
        --win-per-user-install

    - name: Upload Installer Artifact
      uses: actions/upload-artifact@v4
      with:
        name: CleanView-Windows
        path: installer/*.exe

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: Release v1.0.${{ github.run_number }}
        files: |
         installer/*.exe     # or *.dmg on mac
        env:
        GITHUB_TOKEN: ${{ secrets.CV_PAT }}

