# .github/workflows/build-and-release.yml
name: Build and Release Installers

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    strategy:
      # Don't cancel other jobs if one fails
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'

    - name: Build Application and Installer with Maven
      # This single command uses the profiles in pom.xml to create the correct installer
      run: mvn -B clean package

    - name: Upload Installer Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ runner.os }}-installer
        # This path points to where the jpackage command in the pom.xml saves the installer
        path: target/installer/*

  release:
    # This job runs only after all build jobs have successfully completed
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download all installer artifacts
      uses: actions/download-artifact@v4
      with:
        # The path where all artifacts will be downloaded
        path: all-artifacts

    - name: Display structure of downloaded files
      run: ls -R all-artifacts

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        # The tag and release name are generated dynamically
        tag_name: v1.0.${{ github.run_number }}
        name: CleanView v1.0.${{ github.run_number }}
        body: |
          New release of CleanView.
          Installers for Windows and macOS are attached below.
        # Upload all files from all subdirectories of the downloaded artifacts
        files: all-artifacts/**/*
      env:
        # The default GITHUB_TOKEN has the required permissions to create a release
        GITHUB_TOKEN: ${{ secrets.CV_PAT }}
