# .github/workflows/build-and-release.yml
name: Build and Release Installers

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # Creates 3 separate jobs for Windows, macOS (Intel), and macOS (Apple Silicon)
        os: [windows-latest, macos-13, macos-14]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'

    - name: Build Application and Installer with Maven
      run: mvn -B clean package

    - name: Upload Installer Artifact
      uses: actions/upload-artifact@v4
      with:
        # Creates a unique artifact for each OS build to prevent overwrites
        name: ${{ matrix.os }}-installer
        path: target/installer/*

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download all installer artifacts
      uses: actions/download-artifact@v4
      with:
        path: all-artifacts

    - name: Display structure of downloaded files
      run: ls -R all-artifacts

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: CleanView v1.0.${{ github.run_number }}
        body: |
          New release of CleanView.
          
          Installers for Windows, macOS (Intel), and macOS (Apple Silicon) are attached below.
        files: all-artifacts/**/*
      env:
        # Use the standard GITHUB_TOKEN for security and reliability
        GITHUB_TOKEN: ${{ secrets.CV_PAT }}