name: Build and Release Windows Installer

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Verify Maven
      run: mvn -v

    - name: Build app
      run: mvn clean install

    - name: Create installer with jpackage
      shell: cmd
      run: |
        jpackage --type exe ^
        --input target ^
        --dest installer ^
        --name CleanView ^
        --main-jar CleanView-1.0.jar ^
        --main-class com.sampath.pdfviewer.MainApp ^
        --icon src/main/resources/icon.ico ^
        --win-menu ^
        --win-shortcut ^
        --win-dir-chooser ^
        --win-per-user-install

    - name: Verify installer file exists
      shell: cmd
      run: dir installer

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: Release v1.0.${{ github.run_number }}
        files: installer/*.exe
      env:
        GITHUB_TOKEN: ${{ secrets.CV_PAT }}
